name: Docker build and run container test

on:
  push:
    paths:
      - 'contrib/docker/Dockerfile'
  pull_request:
    paths:
      - 'contrib/docker/Dockerfile'
  schedule:
    - cron: '23 17 4,18 * *'
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Check <https://github.com/docker/setup-buildx-action>.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: docker build -t sentencepiece -f contrib/docker/Dockerfile .
      
      - name: 'Test running container (print version)'
        run: |
          timeout 1m docker run --rm sentencepiece spm_train --version
          timeout 1m docker run --rm sentencepiece spm_encode --version
          timeout 1m docker run --rm sentencepiece spm_decode --version
      - name: 'Test running container (trivial training)'
        run: |
          cd "$(mktemp -d tmp.XXXXXX)"
          echo 'a cat sat on a mat' > train.txt
          echo 'a mat is sat by a cat' >> train.txt
          echo 'cat cat cat' >> train.txt
          echo 'sat sat sat' >> train.txt
          echo 'mat mat mat' >> train.txt
          echo 'cat sat mat' >> train.txt
          timeout 1m docker run --rm -v "$(pwd):/data" sentencepiece spm_train --input /data/train.txt --model_prefix /data/m --vocab_size 30 --model_type bpe
          grep cat m.vocab
          grep sat m.vocab
          grep mat m.vocab
